name: firebasestarter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^2.4.0
  device_info: ^2.0.2
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_helpers: ^0.4.0
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  firebase_storage: ^8.1.3
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  image_cropper: ^1.4.1
  image_picker: ^0.8.3+2
  package_info: ^2.0.2
  provider: ^5.0.0
  auth_buttons: ^1.0.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_automation: ^2.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
