name: firebasestarter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^1.0.4
  device_info: ^2.0.0
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  firebase_crashlytics: ^2.0.0
  firebase_helpers: ^0.3.1
  firebase_messaging: ^9.1.1
  firebase_remote_config: ^0.9.0-dev.2
  firebase_storage: ^8.0.3
  flutter_auth_buttons: ^0.9.0
  flutter_svg: ^0.21.0+1
  flutter_swiper: ^1.1.6
  google_fonts: ^2.0.0
  google_sign_in: ^5.0.1
  image_cropper: ^1.4.0
  image_picker: ^0.7.4
  package_info: ^2.0.0
  provider: ^5.0.0

dependency_overrides:
  crypto: ^3.0.0
  http: ^0.13.0
  intl: 0.17.0
  petitparser: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_automation: ^1.4.0
  integration_test: ^1.0.2+2
  intl_translation: ^0.17.10+1

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
